In [3]:
import pytrends
import country_abbrev
from pytrends.request import TrendReq

In [10]:
pytrends = TrendReq(hl='en-US', tz=360)

In [17]:
pytrends.build_payload(kw_list=['migration', 'refugee'], geo=country_abbrev.country_to_abbrev['Mexico'], timeframe= 'all')
pytrends.interest_over_time()

            migration  refugee  isPartial
date
2004-01-01          0        0      False
2004-02-01         21        0      False
2004-03-01         57        0      False
2004-04-01        100       25      False
2004-05-01         29        0      False
...               ...      ...        ...
2022-12-01         10        2      False
2023-01-01         13        2      False
2023-02-01         12        1      False
2023-03-01         14        2      False
2023-04-01         10        2       True

[232 rows x 3 columns]